version: "3"

services:
    web:
        build:
            context: ./apache-php
        ports:
            - 8888:80
        # privileged: true
        volumes:
            - "../study-tdd-laravel/study-tdd-laravel/:/var/www/html"
            # - "./:/var/www/html"
            - "./apache-php/apache.conf:/etc/httpd/conf/httpd.conf"
        container_name: "apache-php"
    db:
        image: mysql:5.7
        env_file: .docker-env
        container_name: "mysql5.7"
        volumes:
          - tdd_laravel_db:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - db
        ports:
            - 8889:80
        env_file: .docker-env
        container_name: "phpmyamin_tdd_laravel"

volumes:
  tdd_laravel_db: